# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package files and install dependencies using pnpm
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copy the source code
COPY src src

# Build the project
RUN pnpm run build

# Use a lighter Node.js image for the runtime
FROM node:22-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy the built artifacts and necessary files from the builder stage
COPY --from=builder /app/dist dist
COPY --from=builder /app/package.json .

# Install only production dependencies
RUN npm install -g pnpm && pnpm install --prod

# Set environment variable for Jina.ai API key
ENV JINAAI_API_KEY=your-jinaai-api-key

# Set the entry point for the container
ENTRYPOINT ["node", "dist/index.js"]